# id: (role, English title, summary)
D = {
'6864': ('Editor', "Yan Hairong: The Landless Workers' Movement in Brazil — What Do Twenty-First-Century Peasants Want?",
  "Field report from Brazil's MST camps on how landless farmers occupy land and rebuild communities through cooperative, collective, and ecological farming. Reissued in 2025."),
'7917': ('Translator', "The Politics Behind the Arepa: Food and Politics in Venezuela",
  "Three Venezuelan scholar-activists trace the country's food crisis to a colonial import dependence, U.S. sanctions, and elite sabotage rather than state failure alone, and document grassroots alternatives."),
'8166': ('Contributor', "May Fourth Youth Night Talk: A Cure for Apathetic, Defeatist Youth",
  "A collective conversation among young members marking the centenary of the May Fourth Movement, sharing the words that sustained their commitment to social change."),
'8432': ('Editor', "Freedom to Marry, Women in Politics: The 'Embroidery Revolution' in a Mountain Village",
  "How an embroidered oral-history project helped rural women in Henan find voice, confidence, and a place in village public life."),
'8471': ('Editor', "Nearly 100 Million Yuan for Irrigation Gone to Waste: Farming Still Depends on the Weather",
  "Investigates why heavily funded small-scale irrigation works fall into disuse, linking the problem to weak village collectives and the absence of organized maintenance."),
'8604': ('Translator & Editor', "Richard Levins: Your Blood Pressure Betrays Your Social Class",
  "Translation of the Harvard ecologist's lecture on how class position is written into the body, and a critique of reductionist epidemiology."),
'8613': ('Editor', "The Essence of Mao's Management Thought: How 'Millet and Rifles' Defeated 'Planes and Tanks'",
  "Lao Tian reads Mao's commitment to flat, mass-line organization as a theory of management, and traces how its erosion after 1949 widened the gap between cadres and the masses."),
'8649': ('Moderator', "Chengshi Lecture No. 22 — Ku Hok Bun: Green Social Work in an Age of Disaster",
  "Lecture on the environmental crises of global capitalism and how green social work can respond, drawing on rural participatory action research in China."),
'8659': ('Editor', "Yi Lianyuan: The Keys to Success of New China's Largest Mass Health Campaign",
  "Explains the success of the schistosomiasis-control campaign through state funding and the flow of medical expertise to the countryside, contrasted with U.S.-led malaria eradication in Africa."),
'8666': ('Editor', "'Once You're Past 45, Even the Market Won't Let You Sell Vegetables'",
  "A privatized wet-market upgrade squeezes vendors and shoppers alike, and exposes everyday age and class discrimination."),
'8680': ('Editor', "Xu Xianglin: Ant Group Drains Farmers Through Financial Channels",
  "A Central Party School economist argues that fintech lending enriches capital rather than agriculture, and makes the case for credit cooperatives within village collectives."),
'8766': ('Editor', "Tao Lujia: A Participant's Account of the Mao–Liu Split over Cooperatives in the Early 1950s",
  "Memoir by a former Shanxi provincial leader on the 1951 debate over pilot agricultural cooperatives and the case for collectivization after land reform."),
'8773': ('Editor', "How Argentina's Land Laws Choked Sustainable Agriculture",
  "Land leasing in Argentina has concentrated farming in fewer, larger operations with heavy chemical use. The piece reads this as a warning for China's accelerating land transfers."),
'8793': ('Editor', "Lao Tian: CCTV's Cynical Scholarship on the Origins of Sandstorms",
  "Uses decades of Chinese geographical research to challenge media narratives that blame farmers and herders for sandstorms."),
'8823': ('Editor', "Pharmaceuticals and Global Capitalism",
  "Sasha Breger Bush on drugs as both a source of profit and a form of 'insurance' that lets people endure the damage capitalism does to bodies and ecosystems."),
'8846': ('Editor', "Jiang Yu: Driving Domestic Demand Through Elder Care, Education, and Health Is Drinking Poison to Quench Thirst",
  "A State Council researcher rebuts the idea of turning basic social services into engines of consumption and profit."),
'8851': ('Editor', "The Specter of Canadian Colonialism: The Cultural Killing of Indigenous Peoples",
  "After the discovery of children's remains at a residential school, an essay arguing that reconciliation requires decolonizing land, history, and knowledge."),
'8858': ('Editor', "Keeping the Original Aspiration — Model Worker Shi Laihe: The Villagers' Well-being as a Lifelong Mission",
  "Portrait of the Party secretary who led Liuzhuang village in Henan from barren floodland to a prosperous collective."),
'8871': ('Editor', "Chengshi Lecture No. 34 — Zhong Xueping: Women and Social Revolution in Chinese and Indian Cinema",
  "A Tufts professor compares films from post-1949 China and post-1947 India to ask how socialist revolution relates to women's liberation."),
'8896': ('Editor', "Mo Yan's Class Bias: On Agricultural Mechanization in the Mao Era",
  "A rebuttal of the novelist's account of Mao-era farming and of his celebration of large agribusiness landholders as 'new farmers.'"),
'8912': ('Transcription', "Chengshi Lecture No. 36 — The Logic of People vs. the Logic of Algorithms: Sun Ping and He Siqi on Delivery Riders and Platforms",
  "A dialogue on delivery riders' working conditions, debt, and gender composition, and on extending social insurance to platform workers."),
'8944': ('Editor', "How to Rescue Peasants from the 'Crossroads' of Bankruptcy: The Dazhai Approach",
  "Excerpts from Zhang Huaiying's memoir of Chen Yonggui and Dazhai on how cooperatives countered re-polarization after land reform."),
'8977': ('Editor', "Yan Hairong: Tearing the Gender Label off Housework",
  "Argues against the gendered division of labor and productivist views of work, and for recognizing social reproduction as social labor."),
'8996': ('Editor', "Lao Tian: How Should We Read Mao's Selected Works Today?",
  "On making Marxist and Maoist theory accessible to young readers through analytical language, practice, and dialectics."),
'9024': ('Editor', "Green Wheat Harvested for Feed: What Should We Really Pay Attention To?",
  "Explains the controversy over cutting immature wheat for silage, and connects it to national grain security and farmers' low incomes."),
'9033': ('Editor', "Vijay Prashad: I Can't Live on Tomorrow's Bread",
  "Tricontinental newsletter tracing the 2022 inflation crisis to U.S. military spending, U.S. consumption, and the Wall Street–dollar–IMF system."),
'9064': ('Editor', "Wang Dan: Sukhomlinsky — The Living Source of Labor Education Is the Collective",
  "An HKU education scholar introduces the Soviet educator's collective, labor-centered pedagogy as an alternative to exam-driven schooling."),
'9069': ('Proofreader', "The Suffocating 'Lungs of the Earth': How Cattle Ranching Devours the Amazon",
  "Translated Washington Post investigation into 'cattle laundering' and how Brazil's beef supply chain drives deforestation."),
'9084': ('Editor', "Zhun Xu: How the Nobel Prize in Economics Enthroned Neoliberalism",
  "Traces the politics behind the economics prize and its role in making market fundamentalism mainstream."),
'9092': ('Editor', "Hu Jing: Jiangsu's Turnaround from Grain Consumer to Grain Producer, 2003–2020",
  "Shows how an industrial powerhouse rebuilt grain self-sufficiency, and argues that food production and industrialization can reinforce each other."),
'9126': ('Editor', "Is Relying on Grain Imports Viable? How the U.S. Uses Food Hegemony to Coerce Other Nations",
  "A 1975 Business Week article on American 'food power,' republished with an introduction on China's food security."),
'9129': ('Subtitle Proofreader', "Screening: The Co-op Wars — Who 'Deserves' Organic Food?",
  "Chinese-subtitled screening and discussion of a documentary on 1970s Minneapolis food co-ops, with two participants in those events."),
'9136': ('Translation Editor', "Populism, Neoliberalism, and Agrarian Movements in Europe",
  "Translation of Mamonova and Franquesa on how neoliberal restructuring fuels right-wing populism in rural Europe, and on the prospects for progressive agrarian politics."),
'9147': ('Editor', "Yan Hairong: The 'American Disease' in the U.S. Labor Movement",
  "Review of Robert Fitch's Solidarity for Sale on union corruption, business unionism, and labor imperialism."),
'9150': ('Editor', "June Nash: The Anthropologist Who Stood with Workers",
  "Profile of the anthropologist whose study of Bolivian tin miners, We Eat the Mines and the Mines Eat Us, founded the anthropology of labor."),
'9158': ('Editor', "John Bellamy Foster: Understanding and Responding to the Global Ecological Crisis",
  "Interview on ecological Marxism, metabolic rift, imperialism, and the idea of an 'environmental proletariat.'"),
'9195': ('Editor', "Lao Tian: Is a Non-Market Path to Technological Innovation Possible?",
  "Reflecting on a hospital research scandal, revisits Mao-era 'technical democracy' that pooled the knowledge of workers and scientists."),
'9203': ('Translator', "Raj Patel: The Political Interests Behind New Agricultural Technology — The Long Green Revolution (I)",
  "Part one of Patel's history of the Green Revolution as a Cold War anti-communist project."),
'9206': ('Translator', "Raj Patel: Debunking the Myths — Three Core Arguments for the Green Revolution — The Long Green Revolution (II)",
  "Part two rebuts claims that Green Revolution technology was scale-neutral, pro-smallholder, and market-driven."),
'9211': ('Translator', "Raj Patel: The New Green Revolution — Agricultural Financialization and Biopolitics — The Long Green Revolution (III)",
  "Part three on the 'New Green Revolution' in Africa as agricultural financialization led by donors, foundations, and agribusiness."),
'9212': ('Editor', "Companion Reading in a Wet Market",
  "Student volunteers run a reading corner for vendors' children in a Shanghai market, as a model of grounded cultural work."),
'9237': ('Translator & Editor', "Was East Germany More Gender-Equal and Better Educated than the West?",
  "Selected translation from Victor Grossman's memoir A Socialist Defector on the GDR's achievements in gender equality and education, and its crises."),
'9243': ('Translator', "The 1949 Asian Women's Conference: All Roads to Women's Liberation Lead to Beijing",
  "Selected translation from Elisabeth Armstrong's Bury the Corpse of Colonialism on the anti-imperialist women's conference held in Beijing."),
'9276': ('Editor', "The Discarded 'Mother Workers' of the Data-Labeling Industry",
  "Reports on rural mothers recruited into AI data-labeling under poverty-alleviation programs, and their double exploitation at work and at home."),
'9292': ('Proofreader', "Recovering Chinese Socialist Science: Pu Zhelong, Entomologist of 'Native and Foreign' Methods",
  "Translation of Sigrid Schmalzer's study of the biological pest-control pioneer who combined peasant knowledge with formal science."),
'9301': ('Translator', "Reflections from an Activist: Looking Back on the Food Sovereignty Movement",
  "Nettie Wiebe, an early La Vía Campesina leader, on the origins of food sovereignty, feminist struggles within the movement, and agroecology."),
'9303': ('Proofreader & Editor', "How to Defeat Big Landlords and Big Capital: Forty Years of Brazil's Landless Workers' Movement",
  "Tricontinental dossier on the MST's tactics, organization, and 'popular agrarian reform.'"),
'9309': ('Translator', "Revisiting the Education Reforms of the 1960s and 70s",
  "Selected translation from Dongping Han's The Unknown Cultural Revolution on how rural education reform in Jimo County expanded schooling and linked learning to production."),
'9320': ('Translator & Editor', "Zhun Xu: Achievements and Challenges of North Korean Agricultural Development",
  "Analyzes the DPRK's rapid early growth, its petrochemical Green Revolution model, and the famine that followed the Soviet collapse."),
'9356': ('Compiler', "2024 in Review: Returning to Histories of Struggle, Agrarian Questions, and Collective Practice",
  "Year-end roundup of the network's most-read articles of 2024."),
'9367': ('Editor', "From Cowherd to General Manager: How Collective Pastoralism Cultivates Leaders",
  "Case study from northern Tibet of a collective herding enterprise and the leader it produced, arguing that collective and individual interests reinforce each other."),
'9371': ('Translator', "Dongping Han: Creating Fairness in Collective Labor — Rural Industrialization in the 1960s",
  "Further translation from The Unknown Cultural Revolution on village enterprises, collective labor, and 'walking on two legs.'"),
'9466': ('Translator & Editor', "How the AI Bubble Is Entangled with Capitalist Crisis",
  "Argues that the U.S. AI boom is a speculative outlet for surplus capital under financialization, whose costs will fall on workers."),
'9476': ('Editor', "When Rural Canteens for the Elderly Aren't Just About the Money",
  "Interview with a Guangzhou social-work NGO on community meal programs, showing that organizing elderly villagers matters more than funding."),
'9509': ('Editor', "The Long War on Iran: New Events, Old Questions",
  "Historian Behrooz Ghamari connects the 2025 strikes on Iran to a century of Western intervention, from the 1953 coup to 'maximum pressure.'"),
'9521': ('Editor', "Chen Mei-hsia: What Is the Real Purpose Behind the U.S. Pause on Arms Sales to Taiwan?",
  "Interview with a Taiwanese public-health scholar on U.S. arms sales, the military-industrial complex, and Taiwanese politics."),
'9525': ('Transcription', "A Conversation on Iran, Anti-Imperialism, and the Future of the Left",
  "Edited record of a debate on how to analyze a war waged by imperial powers against a state with its own internal class oppression."),
'9529': ('Translator', "When Driscoll's Is on Trial: Chemicals, Land, and Labor in the U.S. Strawberry Industry",
  "Translated chapter from Julie Guthman's Wilted on scarce labor and disposable bodies in California's fumigant-dependent strawberry industry."),
'9534': ('Translator', "Where Is Home? Lebanese Farmers, Seeds, and Communities Under Fire",
  "On Israel's war in southern Lebanon and a draft seed law that threatens farmers' right to save and exchange local baladi seeds."),
'9541': ('Translator', "Behind Nepal's Flash Floods: The World Inequality Report on Capitalism's Ecological Exploitation",
  "Translated chapters of the World Inequality Report 2026 on North–South ecological inequality and unpaid reproductive labor, with a critique of its reformist remedies."),
'9544': ('Editor', "The 'Human Kibble' Craze: Why Has Eating Become Just Another Task?",
  "On young workers batch-freezing a week of meals, read as a symptom of overwork and the commodification of social reproduction."),
'7832': ('Editor', 'Food Watch Monthly: Fake Organics in Baby Formula and Vegetables',
  'May 2018 roundup of food-safety news, led by fraudulent organic certification of vegetables and infant formula.'),
'7922': ('Editor', "Overtime Worker: Why Can't I Stop Stress-Eating?",
  'How chronic stress drives overeating, with the reminder that diet can ease stress but not remove its sources.'),
'7952': ('Editor', "Food Watch Monthly: Spicy-Snack Standards, 'Bathed' Hairy Crabs, and Microplastics in the Deep Sea",
  'September 2018 roundup: additive disputes in the spicy-snack industry, counterfeit Yangcheng Lake crabs, and microplastics found in deep-sea life.'),
'7954': ('Editor', "Waste Pickers Keep Our Cities Running. It's Time to Give Them Dignity",
  "On the millions of informal recyclers who sustain China's high recycling rate, and the evictions and stigma they face."),
'8003': ('Editor', "Food Watch Monthly: 'Zombie Meat' Returns and 5,400 Tons of Counterfeit Salt",
  'November 2018 roundup: counterfeit salt, rotten frozen meat, and plasticizers in liquor.'),
'8015': ('Editor', 'Forget Flavorful Origins: Look at What Ministry Canteens Serve',
  "Contrasts China's food-safety scandals with the cheap, safe food in government canteens, and asks why ordinary people cannot have the same."),
'8049': ('Editor', 'School Food-Safety Scandals Keep Recurring. Who Is Harming Our Children?',
  'Reviews repeated cases of spoiled food in school canteens and calls for parent oversight and limits on catering monopolies.'),
'8245': ('Editor', "51 of the World's 100 Most Dangerous Invasive Species Are Now in China",
  'On invasive species in China, most introduced by people, and the roughly 200 billion yuan in annual losses they cause.'),
'8287': ('Editor', "National Day Special: The Socialist Upsurge in China's Countryside, Episode 1: Getting Organized",
  'Transcript of the first episode of a documentary series on agricultural cooperation and collectivization in the 1950s.'),
'8292': ('Editor', 'Qiliying, Henan: Sixty Years of Collective Economy',
  'Final episode of the documentary series, on a township whose collective economy became a model of rural development.'),
'8321': ('Translator & Editor', 'Seeds: Commons or Corporate Property? A Documentary from Eight Latin American Countries',
  'Chinese version of a documentary on peasant struggles across Latin America to protect native seeds against patents and GM seeds.'),
'8325': ('Editor', 'The Pork Problem Is About More Than Rising Prices',
  'Links the 2019 pork price surge to slaughterhouse monopolies, the loss of native breeds, and lax oversight, not only African swine fever.'),
'8367': ('Editor', 'Whales: Our Fate Is in Human Hands',
  'Bathsheba Demuth on the history of commercial whaling and how human markets shaped the fate of whales.'),
'8376': ('Editor', "Mapping China's Hog Capacity: Recovery Means Capital Reshuffling",
  'Shows how the 2019 hog shortage and recovery policies accelerated consolidation, pushing out small and mid-sized farmers.'),
'8408': ('Editor', "Li Ling: New China's Health-Care Model and the Road to a Healthy China",
  'Health economist Li Ling argues that treating hospitals as businesses drives runaway costs, and that public provision is needed.'),
'8413': ('Editor', 'Like the Fangcang Hospitals: How to Fix Health Care',
  "Reads the cooperative spirit of Wuhan's temporary COVID hospitals as a case for public-interest health care over market reform."),
'8446': ('Editor', 'Wang Hui: How Should We Think About a Possible Communist Future Today?',
  "Excerpts Wang Hui's essay on the October Revolution, arguing for reassessing the achievements of twentieth-century socialism."),
'8599': ('Editor', 'Samir Amin: Why Monopoly Capitalism Is Bound to Destroy Itself',
  'Amin on democracy, the peasantry, and ecology as the three challenges that contemporary monopoly capitalism cannot resolve.'),
'8701': ('Editor', 'Chen Yiyuan: How Party-Led Cooperatives in Yantai Mobilize Villagers',
  'Case study of village cooperatives in Shandong that rebuild collective organization by empowering rather than subsidizing smallholders.'),
'8703': ('Author', 'Why Do Imported Cold-Chain Foods Keep Testing Positive? Behind 180,000 Daily U.S. Cases',
  "My own compilation on COVID-19 outbreaks in U.S. meatpacking plants and the global cold chain that links them to China's dinner tables."),
'8750': ('Co-author', "China's Monsanto: Dabeinong's Seed Gamble and GM Corn as a Staple",
  "Collective investigation into Dabeinong, the company behind China's first approved GM corn, and what commercialization means for farmers and consumers."),
'8949': ('Editor', "Fred Engst: The Appeal of the Chinese Revolution in Joan Hinton's Eyes",
  "Joan Hinton's son recounts why his American parents came to China in the 1940s and stayed to work alongside farmers."),
}
